version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:8.11.3
   working_directory: ~/public-holidays
   steps:
     - checkout
     - run:
         name: Build dependencies
         command: yarn
     - run:
         name: Lint
         command: yarn lint
     - run:
         name: Run tests
         command: yarn test

